#!/usr/bin/env bash
# Display "Best School" 10 times
# Display "bad luck" on the 4th time
# Display "good luck" on the 8th time

count=0

while [ $count -lt 10 ]
do
	if [ $count -eq 3 ]
	then
		echo "bad luck"
	elif [ $count -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( count++ ))
done
